<?php

/**
 * @file
 * Contains install and update for Webship Default Content module.
 */

use Drupal\Core\Recipe\Recipe;
use Drupal\Core\Recipe\RecipeRunner;

/**
 * Implements hook_install().
 */
function webship_default_content_install() {

  // Process the default Webship Default Content recipe.
  $default_recipe = Recipe::createFromDirectory(__DIR__ . '/recipes/default');
  RecipeRunner::processRecipe($default_recipe);


}
